image: docker

services:
  - docker:dind

before_script:
  - apk add --no-cache git
  - apk add --no-cache make
  - apk add --no-cache glide
  - export GOPATH=/dekape/go
  - mkdir -p $GOPATH
  - ln -s /builds/dekape $GOPATH/src
  - cd $GOPATH/src/shadow

stages:
  - pushdevel
  - pushprod
  
pushdevel:
  stage: pushdevel
  except:
    - master@dekape/shadow
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - export ENV=development
    - make build push

pushprod:
  stage: pushprod
  only:
    - master@dekape/shadow
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - export ENV=production
    - make build push
