version: '3.4'

services:
  backend:
    image: registry.gitlab.com/sangkuriang-dev/transmissor-be/backend:latest
    env_file: env.production
    container_name: backend
    ports:
      - 44445:44445
    volumes:
      - /tmp:/tmp
    restart: on-failure
