FROM golang:1.13-buster as builder
WORKDIR /go/src
COPY . ./shadow/
RUN apt-get update && apt-get install -yq gcc make
ARG ENV
ARG ARCHFLAG
RUN make -C shadow dependencies
RUN make -C shadow compile

FROM arm32v7/docker:dind as app
WORKDIR /cbi
VOLUME /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static
RUN apk add --update docker-compose
COPY ./deploy/shadow/env.production .env
COPY --from=builder /go/src/shadow/shadow-shadow shadow
CMD ["/cbi/shadow"]
