FROM golang:1.13-buster as builder
WORKDIR /go/src
COPY . ./shadow/
RUN apt-get update && apt-get install -yq gcc make go-dep
ARG ENV
ARG ARCHFLAG
RUN cd shadow && dep ensure -v
RUN make -C shadow compile

FROM arm32v7/alpine as app
WORKDIR /cbi
COPY ./deploy/shadow/env.production .env
COPY --from=builder /go/src/shadow/shadow-shadow shadow
CMD ["/cbi/shadow"]
