FROM golang:1.13-alpine as builder
WORKDIR /go/src
COPY . ./shadow/
RUN apk update
RUN apk add git
RUN apk add glide
RUN apk add make
ARG ENV
ARG ARCHFLAG
RUN make -C shadow dependencies
RUN make -C shadow compile

FROM alpine:latest as app
WORKDIR /cbi
COPY ./deploy/shadow/env.development .env
COPY --from=builder /go/src/shadow/shadow-shadow shadow
CMD ["/cbi/shadow"]
